apiVersion: v1

kind: Service

metadata:
  name: model-service
  labels:
    app: model-service

spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5001
  selector:
    app: model-pod
